- name: Pull and Run Backend
  docker_container:
    name: backend
    image: backend-app
    state: started
    restart_policy: always
    published_ports:
      - "3000:3000"

- name: Pull and Run Frontend
  docker_container:
    name: frontend
    image: frontend-app
    state: started
    restart_policy: always
    published_ports:
      - "{{ app_port }}:80"

- name: Pull and Run Database
  docker_container:
    name: database
    image: database-app
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
    published_ports:
      - "{{ db_port }}:3306"
